import 'package:flutter/material.dart';

final List<Map<String, dynamic>> routes = [
  {
    "Route": "Route 1",
    "Zone": false,
    "Top": false,
    "Zone Points": 100,
    "Top Points": 50,
    "Zone Weight": 20,
    "Top Weight": 10,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false,
  },
  {
    "Route": "Route 2",
    "Zone": false,
    "Top": false,
    "Zone Points": 100,
    "Top Points": 50,
    "Zone Weight": 21,
    "Top Weight": 11,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false,
  },
  {
    "Route": "Route 3",
    "Zone": false,
    "Top": false,
    "Zone Points": 95,
    "Top Points": 50,
    "Zone Weight": 22,
    "Top Weight": 12,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false,
  },
  {
    "Route": "Route 4",
    "Zone": false,
    "Top": false,
    "Zone Points": 95,
    "Top Points": 50,
    "Zone Weight": 23,
    "Top Weight": 13,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false,
  },
  {
    "Route": "Route 5",
    "Zone": false,
    "Top": false,
    "Zone Points": 95,
    "Top Points": 45,
    "Zone Weight": 24,
    "Top Weight": 14,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false,
  },
  {
    "Route": "Route 6",
    "Zone": false,
    "Top": false,
    "Zone Points": 90,
    "Top Points": 45,
    "Zone Weight": 25,
    "Top Weight": 15,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 7",
    "Zone": false,
    "Top": false,
    "Zone Points": 95,
    "Top Points": 45,
    "Zone Weight": 26,
    "Top Weight": 16,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 8",
    "Zone": false,
    "Top": false,
    "Zone Points": 90,
    "Top Points": 45,
    "Zone Weight": 27,
    "Top Weight": 17,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 9",
    "Zone": false,
    "Top": false,
    "Zone Points": 90,
    "Top Points": 45,
    "Zone Weight": 28,
    "Top Weight": 18,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 10",
    "Zone": false,
    "Top": false,
    "Zone Points": 85,
    "Top Points": 40,
    "Zone Weight": 29,
    "Top Weight": 19,
    "Required for Ibex Male": false,
    "Required for Ibex Female": true,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 11",
    "Zone": false,
    "Top": false,
    "Zone Points": 80,
    "Top Points": 40,
    "Zone Weight": 30,
    "Top Weight": 20,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 12",
    "Zone": false,
    "Top": false,
    "Zone Points": 80,
    "Top Points": 40,
    "Zone Weight": 31,
    "Top Weight": 21,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 13",
    "Zone": false,
    "Top": false,
    "Zone Points": 80,
    "Top Points": 40,
    "Zone Weight": 32,
    "Top Weight": 22,
    "Required for Ibex Male": true,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 14",
    "Zone": false,
    "Top": false,
    "Zone Points": 75,
    "Top Points": 35,
    "Zone Weight": 33,
    "Top Weight": 23,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 15",
    "Zone": false,
    "Top": false,
    "Zone Points": 75,
    "Top Points": 35,
    "Zone Weight": 34,
    "Top Weight": 24,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 16",
    "Zone": false,
    "Top": false,
    "Zone Points": 70,
    "Top Points": 35,
    "Zone Weight": 35,
    "Top Weight": 25,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 17",
    "Zone": false,
    "Top": false,
    "Zone Points": 70,
    "Top Points": 35,
    "Zone Weight": 36,
    "Top Weight": 26,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 18",
    "Zone": false,
    "Top": false,
    "Zone Points": 65,
    "Top Points": 30,
    "Zone Weight": 37,
    "Top Weight": 27,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 19",
    "Zone": false,
    "Top": false,
    "Zone Points": 65,
    "Top Points": 30,
    "Zone Weight": 38,
    "Top Weight": 28,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.black,
    "isTop10": false,
  },
  {
    "Route": "Route 20",
    "Zone": false,
    "Top": false,
    "Zone Points": 60,
    "Top Points": 30,
    "Zone Weight": 39,
    "Top Weight": 29,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.black,
    "isTop10": false,
  },
];
