import 'package:flutter/material.dart';

final List<Map<String, dynamic>> routes = [
  {
    "Route": "Route 1",
    "Zone": false,
    "Top": false,
    "Zone Points": 100,
    "Top Points": 50,
    "Zone Weight": 20,
    "Top Weight": 30,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false,
  },
  {
    "Route": "Route 2",
    "Zone": false,
    "Top": false,
    "Zone Points": 100,
    "Top Points": 50,
    "Zone Weight": 20,
    "Top Weight": 31,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false,
  },
  {
    "Route": "Route 3",
    "Zone": false,
    "Top": false,
    "Zone Points": 95,
    "Top Points": 50,
    "Zone Weight": 22,
    "Top Weight": 28,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false,
  },
  {
    "Route": "Route 4",
    "Zone": false,
    "Top": false,
    "Zone Points": 95,
    "Top Points": 50,
    "Zone Weight": 22,
    "Top Weight": 28,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false,
  },
  {
    "Route": "Route 5",
    "Zone": false,
    "Top": false,
    "Zone Points": 95,
    "Top Points": 45,
    "Zone Weight": 22,
    "Top Weight": 29,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false,
  },
  {
    "Route": "Route 6",
    "Zone": false,
    "Top": false,
    "Zone Points": 90,
    "Top Points": 45,
    "Zone Weight": 23,
    "Top Weight": 29,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 7",
    "Zone": false,
    "Top": false,
    "Zone Points": 95,
    "Top Points": 45,
    "Zone Weight": 22,
    "Top Weight": 29,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 8",
    "Zone": false,
    "Top": false,
    "Zone Points": 90,
    "Top Points": 45,
    "Zone Weight": 23,
    "Top Weight": 29,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 9",
    "Zone": false,
    "Top": false,
    "Zone Points": 90,
    "Top Points": 45,
    "Zone Weight": 24,
    "Top Weight": 30,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 10",
    "Zone": false,
    "Top": false,
    "Zone Points": 85,
    "Top Points": 40,
    "Zone Weight": 24,
    "Top Weight": 30,
    "Required for Ibex Male": false,
    "Required for Ibex Female": true,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 11",
    "Zone": false,
    "Top": false,
    "Zone Points": 80,
    "Top Points": 40,
    "Zone Weight": 25,
    "Top Weight": 31,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 12",
    "Zone": false,
    "Top": false,
    "Zone Points": 80,
    "Top Points": 40,
    "Zone Weight": 25,
    "Top Weight": 31,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false,
  },
  {
    "Route": "Route 13",
    "Zone": false,
    "Top": false,
    "Zone Points": 80,
    "Top Points": 40,
    "Zone Weight": 26,
    "Top Weight": 32,
    "Required for Ibex Male": true,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 14",
    "Zone": false,
    "Top": false,
    "Zone Points": 75,
    "Top Points": 35,
    "Zone Weight": 26,
    "Top Weight": 32,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 15",
    "Zone": false,
    "Top": false,
    "Zone Points": 75,
    "Top Points": 35,
    "Zone Weight": 27,
    "Top Weight": 33,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 16",
    "Zone": false,
    "Top": false,
    "Zone Points": 70,
    "Top Points": 35,
    "Zone Weight": 27,
    "Top Weight": 33,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 17",
    "Zone": false,
    "Top": false,
    "Zone Points": 70,
    "Top Points": 35,
    "Zone Weight": 28,
    "Top Weight": 34,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 18",
    "Zone": false,
    "Top": false,
    "Zone Points": 65,
    "Top Points": 30,
    "Zone Weight": 28,
    "Top Weight": 34,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.purple,
    "isTop10": false,
  },
  {
    "Route": "Route 19",
    "Zone": false,
    "Top": false,
    "Zone Points": 65,
    "Top Points": 30,
    "Zone Weight": 29,
    "Top Weight": 35,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.black,
    "isTop10": false,
  },
  {
    "Route": "Route 20",
    "Zone": false,
    "Top": false,
    "Zone Points": 60,
    "Top Points": 30,
    "Zone Weight": 29,
    "Top Weight": 35,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.black,
    "isTop10": false,
  },
];
final List<Map<String, dynamic>> routesCrest16 = [
  {
    "Route": "Route 1",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 1,
    "Top Weight": 10 * 1,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 2",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 2,
    "Top Weight": 10 * 2,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 3",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 3,
    "Top Weight": 10 * 3,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 4",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 4,
    "Top Weight": 10 * 4,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 5",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 5,
    "Top Weight": 10 * 5,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 6",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 6,
    "Top Weight": 10 * 6,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 7",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 7,
    "Top Weight": 10 * 7,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 8",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 8,
    "Top Weight": 10 * 8,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 9",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 9,
    "Top Weight": 10 * 9,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 10",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 10,
    "Top Weight": 10 * 10,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 11",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 11,
    "Top Weight": 10 * 11,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 12",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 12,
    "Top Weight": 10 * 12,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 13",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 13,
    "Top Weight": 10 * 13,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 14",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 14,
    "Top Weight": 10 * 14,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 15",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 15,
    "Top Weight": 10 * 15,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 16",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 16,
    "Top Weight": 10 * 16,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
];
final List<Map<String, dynamic>> baseCamp = [
  {
    "Route": "Route 1",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 1,
    "Top Weight": 10 * 1,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 2",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 2,
    "Top Weight": 10 * 2,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 3",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 3,
    "Top Weight": 10 * 3,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false
  },
  {
    "Route": "Route 4",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 4,
    "Top Weight": 10 * 4,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false
  },
  {
    "Route": "Route 5",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 5,
    "Top Weight": 10 * 5,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false
  },
  {
    "Route": "Route 6",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 6,
    "Top Weight": 10 * 6,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 7",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 7,
    "Top Weight": 10 * 7,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 8",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 8,
    "Top Weight": 10 * 8,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 9",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 9,
    "Top Weight": 10 * 9,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 10",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 10,
    "Top Weight": 10 * 10,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 11",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 11,
    "Top Weight": 10 * 11,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 12",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 12,
    "Top Weight": 10 * 12,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 13",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 13,
    "Top Weight": 10 * 13,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false
  },
  {
    "Route": "Route 14",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 14,
    "Top Weight": 10 * 14,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false
  },
  {
    "Route": "Route 15",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 15,
    "Top Weight": 10 * 15,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false
  },
  {
    "Route": "Route 16",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 16,
    "Top Weight": 10 * 16,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false
  },
  {
    "Route": "Route 17",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 17,
    "Top Weight": 10 * 17,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.purple,
    "isTop10": false
  },
  {
    "Route": "Route 18",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 18,
    "Top Weight": 10 * 18,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.purple,
    "isTop10": false
  },
  {
    "Route": "Route 19",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 19,
    "Top Weight": 10 * 19,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.black,
    "isTop10": false
  },
  {
    "Route": "Route 20",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 20,
    "Top Weight": 10 * 20,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.purple,
    "Color2": Colors.black,
    "isTop10": false
  },
];
final List<Map<String, dynamic>> Crest16 = [
  {
    "Route": "Route 1",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 1,
    "Top Weight": 10 * 1,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 2",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 2,
    "Top Weight": 10 * 2,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.yellow,
    "isTop10": false
  },
  {
    "Route": "Route 3",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 3,
    "Top Weight": 10 * 3,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false
  },
  {
    "Route": "Route 4",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 4,
    "Top Weight": 10 * 4,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false
  },
  {
    "Route": "Route 5",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 5,
    "Top Weight": 10 * 5,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.green,
    "isTop10": false
  },
  {
    "Route": "Route 6",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 6,
    "Top Weight": 10 * 6,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 7",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 7,
    "Top Weight": 10 * 7,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 8",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 8,
    "Top Weight": 10 * 8,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 9",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 9,
    "Top Weight": 10 * 9,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.green,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 10",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 10,
    "Top Weight": 10 * 10,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 11",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 11,
    "Top Weight": 10 * 11,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 12",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 12,
    "Top Weight": 10 * 12,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.blue,
    "isTop10": false
  },
  {
    "Route": "Route 13",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 13,
    "Top Weight": 10 * 13,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false
  },
  {
    "Route": "Route 14",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 14,
    "Top Weight": 10 * 14,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false
  },
  {
    "Route": "Route 15",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 15,
    "Top Weight": 10 * 15,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false
  },
  {
    "Route": "Route 16",
    "Zone": false,
    "Top": false,
    "Zone Points": 5,
    "Top Points": 10,
    "Zone Weight": 5 * 16,
    "Top Weight": 10 * 16,
    "Required for Ibex Male": false,
    "Required for Ibex Female": false,
    "Color1": Colors.blue,
    "Color2": Colors.purple,
    "isTop10": false
  },
];
